# Generated by Django 5.0.7 on 2024-07-31 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='desc',
            new_name='description',
        ),
    ]
